version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
  browser-tools: circleci/browser-tools@1.2.4
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front-End Install
          command: |
            npm run front-install
      - run:
          name: Back-End Install
          command: |
            npm run back-install
      - run:
          name: Front-End Build
          command: |
            npm run front-build
      - run:
          name: Back-End Build
          command: |
            npm run back-build
